# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d8e0b8dfa68704ddc3db45043d27623ee90b3ed613b752e9801f20aab210efbf4b361a39c7912a168b437f26aed1bb45e682f89aadc21103d48c50be8f04a1b2

test:
  secret_key_base: a55c63028c800f6afcf3b92e46c51760d4332f1553586da6ece74a271711b9590421b46c3afcde57af17929c235d1131d5f9f4fef349d9afd86b7c9353205cb0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
